### PR TITLE
Add transformTemplateHtml

### PR DESCRIPTION
**Pull request by JonesChi**
Allow to transform the html of a template before it is rendered.

### CODE REVIEW

**Comment by emosheeep** [comment]
Could you describe the situations you've encoutered?

**Comment by JonesChi** [comment]
> Could you please describe the situations you've encoutered?

This feature is inspired by transformIndexHtml, please refer to https://vitejs.dev/guide/api-plugin#transformindexhtml
It helps when you want to build multiple websites from the same source.

**Comment by emosheeep** [comment]
> build multiple websites from the same source

I got it, it helps customize something before building.

**Comment by emosheeep** [comment]
I modified something and have published v1.10.0, you can have a try.

**Pull request merged**
